server:
  port: 8080
spring:
  application:
    name: agenda-telefonica
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/agenda_servico?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306
    schemas: agenda_servico
    user: root
    password: root
    baselineOnMigrate: true
    validateOnMigrate: false
opentracing:
  jaeger:
    service-name: agenda-telefonica
    udp-sender:
      host: localhost
      port: 6831
    sampler-type: const
    sampler-param: 1
